- name: frontend code setup
  hosts: all
  become: yes
  tasks:
  - name: Installing Nginx
    ansible.builtin.dnf:
      name: nginx
      state: installed

  - name: Remove previous content
    ansible.builtin.file:
      path: rm -rf /usr/share/nginx/html/*
      state: absent

  - name: Create a directory
    ansible.builtin.file:
      path: /usr/share/nginx/html/*
      state: directory

  - name: Download a file
    ansible.builtin.get_url:
      url: https://expense-artifacts.s3.amazonaws.com/frontend.zip
      dest: /tmp/frontend.zip

  - name: create nginx configuration
    ansible.builtin.copy:
      src: expense.conf
      dest: /etc/nginx/default.d/expense.conf

  #  -Restart nginx
  #  -Starting Nginx
  #ansible.builtin.systemd
