- name: Verify NodeJS
  ansible.builtin.shell: type npm
  register: npm
  ignore_errors: yes

- name: Install NodeJS
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash
  when: npm.rc != 0

- name: Install NodeJS
  ansible.builtin.dnf:
    name: nodejs
  when: npm.rc != 0

- name: Add application user
  ansible.builtin.user:
    name: expense

- name: run common code
  ansible.builtin.import_role:
    name: common
    tasks_from: app_prere.yml

- name: Install NodeJS dependencies
  ansible.builtin.shell: npm install
  args:
    chdir: /app


- name: set up backend service
  ansible.builtin.template:
    src: backend.service
    dest: /etc/systemd/system/backend.service

- name: install client
  ansible.builtin.dnf:
    name: mysql

- name: Load Schema
  ansible.builtin.shell: mysql -h {{ lookup('aws_ssm', 'expenseProject-sql', region='us-east-1' ) }} -uroot -p{{ lookup('aws_ssm', 'sql-password', region='us-east-1' ) }} < /app/schema/backend.sql

- name: start backend service
  ansible.builtin.systemd:
    name: backend
    state: started
    enabled: yes
    daemon-reload: yes

- name: install node exporter
  ansible.builtin.import_role:
    name: prometheus
    tasks_from: node-exporter