- name: Setup Repos
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name: Install node js
  ansible.builtin.dnf:
    name: nodejs


- name: Add application user
  ansible.builtin.user:
    name: expense

- name: run common code
  ansible.builtin.import_role:
    name: common
    tasks_from: app_prere

- name: Install NodeJS dependencies
  ansible.builtin.shell: npm install
  args:
    chdir: /app


- name: set up backend service
  ansible.builtin.copy:
    src: backend.service
    dest: /etc/systemd/system/backend.service

- name: install client
  ansible.builtin.dnf:
    name: mysql

- name: Load Schema
  ansible.builtin.shell: mysql -h sql.varraj20316.online -uroot -pExpenseApp@1 < /app/schema/backend.sql

- name: start backend service
  ansible.builtin.systemd:
    name: backend
    state: started
    enabled: yes
    daemon-reload: yes

