- name: copy my sql repo
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: Disable dnf module mysql
  ansible.builtin.shell: dnf module disable mysql -y

- name: Install community server
  ansible.builtin.dnf:
    name: mysql-community-server
    state: present

- name: Start my sql service
  ansible.builtin.systemd:
    name: mysqld
    state: restarted
    enabled: yes

- name: My sql secure installation
  ansible.builtin.shell: mysql_secure_installation --set-root-pass {{ lookup('aws_ssm', 'sql-password', region='us-east-1' ) }}
