- name: Copy prometheus configuration
  ansible.builtin.template:
    src: main.yml
    dest: /opt/prometheus/main.yml

- name: restart prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: restarted
