- name: download node exporter
  ansible.builtin.unarchive:
    src: "https://github.com/prometheus/node_exporter/releases/download/v{{node_exporter_version}}/node_exporter-{{node_exporter_version}}.linux-amd64.tar.gz"
    dest: /opt
    remote_src: yes

- name: copy node exporter file
  ansible.builtin.template:
    src: node_exporter.service
    dest: /etc/systemd/system/node_exporter.service

- name: Restart node exporter
  ansible.builtin.systemd:
    name: node-exporter
    state: restarted
    enabled: yes
    daemon-reload : yes

