route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'Mail Alert'

receivers:
  - name: 'Mail Alert'
    email_configs:
      - smarthost: 'email-smtp.us-east-1.amazonaws.com:587'
#        auth_username: {{ lookup('aws_ssm', 'SMTP_UserName', region='us-east-1' ) }}
#        auth_password: {{ lookup('aws_ssm', 'SMTP_Password', region='us-east-1' ) }}
        auth_username: 'AKIA2MKQHN5TN4S5ZIZ2'
        auth_password: 'BAUdf4BvuWfI57z2m9+ISSI9l2trqut0wVR1OSsuqdtZ'
        from: varnitach@gmail.com
        to: varnitach@gmail.com
        headers:
        subject: 'Prometheus Mail Alerts'

inhibit_rules:
  - source_match:
      severity: 'critical'
    equal: ['alertname', 'dev', 'instance']
