groups:
  - name: ExpenxeProjectalerts
    rules:
      - alert: ServerDownAlert
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: Server Down Alert

      - alert: FrontendServiceDownAlert
        expr: node_systemd_unit_state{exported_name="nginx.service", state="active"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: frontend Server Down Alert

      - alert: BackendServiceDownAlert
        expr: node_systemd_unit_state{exported_name="backend.service", state="active"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: Backend service Down Alert

      - alert: MySQLServiceDownAlert
        expr: node_systemd_unit_state{exported_name="mysqld.service", state="active"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: My sql service Down Alert

      - alert: MemoryusageAlert
        expr: 100-(node_memory_MemFree_bytes+node_memory_Cached_bytes+node_memory_Buffers_bytes)/node_memory_MemTotal_bytes*100 > 80
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: Large memory consume Alert

      - alert: CPUusageAlert
        expr: 100-avg by(name)(rate(node_cpu_seconds_total{mode="idle"}[1m]))*100 > 80
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: Large CPU consume Alert